version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX}-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX}-php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX}-node
    ports:
      - "4200:4200"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    tty: true
    networks:
      - appnet

  postgresql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX}-postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - appnet

volumes:
  db:

networks:
  appnet:
    driver: "bridge"
