version: "3.3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: application-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: application-php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: application-node
    working_dir: /var/www/html
    ports:
      - "4200:4200"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    tty: true
    networks:
      - appnet

  postgresql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: application-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - appnet

volumes:
  pgdata:
    external: true

networks:
  appnet:
    driver: "bridge"